// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Sprint3.Persistence;

#nullable disable

namespace Sprint3.Migrations
{
    [DbContext(typeof(OracleDbContext))]
    partial class OracleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sprint3.Models.ComportamentoNegocios", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<long>("FrequenciaUso")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("InteracoesPlataforma")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("UsoRecursosEspecificos")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("ComportamentoNegocios");
                });

            modelBuilder.Entity("Sprint3.Models.DesempenhoFinanceiro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("Crescimento")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("Lucro")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("Receita")
                        .HasColumnType("BINARY_DOUBLE");

                    b.HasKey("Id");

                    b.ToTable("DesempenhoFinanceiro");
                });

            modelBuilder.Entity("Sprint3.Models.TendenciasGastos", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("Ano")
                        .HasColumnType("NUMBER(19)");

                    b.Property<double>("GastoAutomacao")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("GastoMarketing")
                        .HasColumnType("BINARY_DOUBLE");

                    b.HasKey("Id");

                    b.ToTable("TendenciasGastos");
                });
#pragma warning restore 612, 618
        }
    }
}
